services:

    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    DsElasticSearchBundle\Builder\ClientBuilderInterface: '@DsElasticSearchBundle\Builder\ClientBuilder'
    DsElasticSearchBundle\Builder\ClientBuilder: ~
