services:

    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    DsElasticSearchBundle\OutputChannel\Filter\AggregationFilter:
        tags:
            - { name: dynamic_search.index.filter, identifier: aggregation, index_provider: elasticsearch }

    DsElasticSearchBundle\OutputChannel\Filter\CompositeAggregationFilter:
        tags:
            - { name: dynamic_search.index.filter, identifier: composite_aggregation, index_provider: elasticsearch }

    DsElasticSearchBundle\OutputChannel\Filter\RangeAggregationFilter:
        tags:
            - { name: dynamic_search.index.filter, identifier: range_aggregation, index_provider: elasticsearch }

    DsElasticSearchBundle\OutputChannel\Filter\GeoDistanceFilter:
        tags:
            - { name: dynamic_search.index.filter, identifier: geo_distance, index_provider: elasticsearch }
